const TRANSLATIONS = {
  zh: {
    // Nav
    logo: '翰墨方舟',
    nav_teaching: 'AI教学',
    nav_creative: '文创生成',
    nav_shop: '文创电商',
    nav_community: '社区',
    nav_profile: '个人中心',
    nav_start: '立即体验',
    lang_btn: 'EN',

    // Index hero
    hero_explore: '探索功能',
    hero_how: '了解流程',

    // Index features
    features_title: '三大核心功能',
    features_sub: '技术驱动体验，体验促进消费',
    f1_title: 'AI 辅助教学',
    f1_desc: '拍照上传练习作品，平台通过 OpenCV 提取字迹骨架，与专业书法家标准进行比对，提供个性化练习建议，实现低门槛、高效率的书法学习体验。',
    f1_tag: '骨架比对 · 智能点评',
    f2_title: '一键文创生成',
    f2_desc: '输入文字或上传书法作品，从极简相框、中式卷轴、T恤印花、手机壳等模板中选择，AI 即时渲染产品预览图，满意即可一键下单。',
    f2_tag: 'AI渲染 · 即时预览',
    f3_title: '跨境文创电商',
    f3_desc: '分层产品体系覆盖新手包、进阶包、礼盒装、订阅盒等多种形式，通过跨境供应链实现全球配送，构建学习驱动消费的商业闭环。',
    f3_tag: '全球配送 · 商业闭环',

    // Index how
    how_title: '使用流程',
    how_sub: '四步完成从练习到文创的全链路体验',
    step1_title: '练习书法',
    step1_desc: '临摹字帖，完成书法练习',
    step2_title: '拍照上传',
    step2_desc: 'AI 智能识别点评',
    step3_title: '选择模板',
    step3_desc: '挑选心仪文创产品模板',
    step4_title: '一键下单',
    step4_desc: '预览满意，下单全球配送',

    // Index products
    products_title: '文创产品系列',
    products_sub: '将书法之美融入日常生活',
    p1_title: '极简相框', p1_desc: '现代简约风格，书法装饰画',
    p2_title: '中式卷轴', p2_desc: '传统工艺，典雅收藏佳品',
    p3_title: 'T恤印花', p3_desc: '个性定制，穿出书法风尚',
    p4_title: '手机壳', p4_desc: '随身携带，展示书法之美',
    p5_title: '礼盒套装', p5_desc: '精美包装，馈赠佳选',
    p6_title: '订阅盒', p6_desc: '每月惊喜，持续学习成长',

    // Index CTA
    cta_title: '开启书法新旅程',
    cta_sub: '加入翰墨方舟，让传统书法焕发现代光彩',
    cta_btn: '立即体验',

    // Footer
    footer: '© 2026 翰墨方舟 · 书法学习与文创平台 · 传承经典，创造未来',
    footer_sub: '© 2026 翰墨方舟 · 传承经典，创造未来',

    // Teaching
    teaching_title: 'AI 书法教学',
    teaching_sub: '分层课程 · 智能测评 · 打卡激励',
    tab_courses: '分层课程',
    tab_eval: '智能测评',
    tab_checkin: '书法打卡',
    choose_style: '选择书体',
    kai: '楷', kai_name: '楷书', kai_desc: '端正规范，入门首选',
    xing: '行', xing_name: '行书', xing_desc: '流畅自然，实用性强',
    li: '隶', li_name: '隶书', li_desc: '古朴厚重，历史悠久',
    zhuan: '篆', zhuan_name: '篆书', zhuan_desc: '古雅精致，艺术价值高',
    course_list_title: '楷书入门课程',
    course_list_sub: '笔画 → 偏旁 → 结字 → 章法，每节 10-15 分钟',
    c1_title: '第1课：横竖撇捺基本笔画', c1_desc: '掌握四大基础笔画的运笔方法', c1_time: '12分钟', c1_status: '已完成',
    c2_title: '第2课：折钩挑点笔画', c2_desc: '学习折、钩、挑、点的写法', c2_time: '10分钟', c2_status: '已完成',
    c3_title: '第3课：常用偏旁部首', c3_desc: '三点水、木字旁、口字旁等', c3_time: '15分钟', c3_status: '进行中',
    c4_title: '第4课：字的间架结构', c4_desc: '左右结构、上下结构的布局原则', c4_time: '15分钟', c4_status: '未解锁',
    c5_title: '第5课：简单章法入门', c5_desc: '行距、字距与整体布局', c5_time: '12分钟', c5_status: '未解锁',
    continue_btn: '继续学习第3课',
    eval_instant_title: '即时测评', eval_instant_desc: '上传书法作品，AI 提取字迹骨架与专业标准比对，生成评分与改进建议。',
    eval_stage_title: '阶段测评', eval_stage_desc: '完成阶段课程后进行综合测评，生成详细报告，展示学习成果与薄弱环节。',
    upload_hint: '点击上传书法作品照片',
    upload_hint2: '支持 JPG / PNG，建议在自然光下拍摄',
    last_eval: '上次测评结果',
    score_stroke: '笔画规范', score_struct: '结字布局', score_layout: '章法整体', score_total: '综合评分',
    ai_advice: 'AI建议：横画收笔力度不足，建议加强"横"的专项练习；结字整体偏左，注意重心居中。',
    streak_label: '当前连续打卡', streak_num: '14 天', streak_hint: '再坚持 7 天即可获得新手包奖励！',
    checkin_btn: '今日打卡',
    month_record: '本月打卡记录',
    week_days: ['一','二','三','四','五','六','日'],
    reward_title: '打卡奖励进度',
    reward_hint: '完成21天连续打卡，免费获得新手文房套装',

    // Creative
    creative_title: '一键文创生成',
    creative_sub: '上传作品或输入文字，即刻生成专属文创产品',
    input_panel: '内容输入',
    upload_calligraphy: '上传书法作品照片',
    text_label: '或输入文字（英文名、祝福语、词句）',
    text_placeholder: '例：福、山高水长、Happy New Year…',
    tpl_panel: '选择模板',
    tpl1: '极简相框', tpl2: '中式卷轴', tpl3: 'T恤印花', tpl4: '手机壳', tpl5: '折扇', tpl6: '礼盒套装',
    generate_btn: '生成效果预览',
    preview_panel: '效果预览',
    preview_label_suffix: ' · 预览效果',
    order_btn: '一键下单',
    regen_btn: '重新生成',
    preview_note: '下单后系统自动生成高清印刷文件，对接合作厂商生产配送',

    // Shop
    shop_title: '跨境文创电商',
    shop_sub: '文房用品 · 书法文创 · 全球配送',
    recommend_title: '智能推荐',
    recommend_sub: '根据你当前学习阶段（楷书·偏旁练习）为你推荐',
    recommend_badge: '学习推荐',
    add_cart: '加入购物车',
    rec_stone_title: '端砚（初学款）',
    rec_stone_desc: '适合偏旁练习阶段，天然石材，发墨细腻',
    rec_paper_title: '生宣练习纸（50张）',
    rec_paper_desc: '专为偏旁阶段设计，吸墨均匀，适合临摹',
    buy: '购买',
    customize: '定制',
    subscribe: '订阅',
    all_products: '全部商品',
    all_products_sub: '文房用品与书法文创，构建学习消费闭环',
    filter_all: '全部', filter_stationery: '文房用品', filter_creative: '书法文创', filter_bundle: '套装礼盒',

    // Community
    community_title: '书法文化社区',
    community_sub: '分享作品 · 交流切磋 · 共同成长',
    post_btn: '+ 发布我的书法作品',
    post1_name: '云墨居士', post1_time: '2小时前 · 行书练习', post1_text: '练习永字有一段时间，感觉目前的写法还不够自然，请各位老师指点！',
    post2_name: '山水间', post2_time: '5小时前 · 楷书练习', post2_text: '山高水长四个字，练习了两周，终于有点感觉了，用翰墨方舟的AI测评打了88分，继续加油！',
    post3_name: '竹影清风', post3_time: '昨天 · 楷书练习', post3_text: '楷书福字，准备做成定制相框送给父母，学习效果超出预期',
    share: '↗ 分享',
    activity1_badge: '进行中', activity1_title: '四月打卡挑战', activity1_desc: '坚持21天每日练习打卡，完成即可获得新手文房套装奖励。', activity1_count: '已有 1,248 人参与', activity1_btn: '立即参与',
    activity2_badge: '即将开始', activity2_title: '五月主题创作：春', activity2_desc: '以"春"为主题创作书法作品，优秀作品将展示于首页并获得积分奖励。', activity2_date: '5月1日开始',
    top_creators: '优秀创作者',
    likes_prefix: '获赞 ',

    // Profile
    profile_title: '个人中心',
    profile_sub: '学习数据 · 订单管理 · 积分中心',
    user_name: '翰墨学员', user_days: '加入 32 天', user_level: '楷书·进阶中',
    menu_data: '📊 学习数据', menu_orders: '📦 我的订单', menu_points: '⭐ 积分中心',
    stat_days: '学习天数', stat_courses: '完成课程', stat_practice: '练习次数', stat_streak: '连续打卡',
    radar_title: '各维度得分分析',
    radar_labels: ['笔画', '结字', '章法', '平均'],
    spend_title: '消费数据',
    spend_total: '累计消费', spend_items: '购买商品', spend_custom: '定制次数', spend_months: '订阅月数',
    order1_name: '书法定制相框', order1_date: '2026-04-10 · 订单号 HM20260410001', order1_status: '配送中',
    order2_name: '新手礼盒套装', order2_date: '2026-03-28 · 订单号 HM20260328002', order2_status: '已完成',
    order3_name: '月度订阅盒 · 4月', order3_date: '2026-04-01 · 订单号 HM20260401003', order3_status: '备货中',
    points_label: '当前积分', points_exchange: '积分兑换',
    pt1_name: '完成课程第2课', pt2_name: '上传练习作品', pt3_name: '购买新手礼盒',
  },

  en: {
    logo: 'InkArk',
    nav_teaching: 'AI Teaching',
    nav_creative: 'Creative Gen',
    nav_shop: 'Shop',
    nav_community: 'Community',
    nav_profile: 'Profile',
    nav_start: 'Get Started',
    lang_btn: '中文',

    hero_explore: 'Explore Features',
    hero_how: 'How It Works',

    features_title: 'Three Core Features',
    features_sub: 'Technology-driven experience, experience-driven commerce',
    f1_title: 'AI-Assisted Teaching',
    f1_desc: 'Upload practice photos. The platform uses OpenCV to extract stroke skeletons, compares them with master calligrapher standards, and provides personalized improvement suggestions.',
    f1_tag: 'Skeleton Analysis · Smart Feedback',
    f2_title: 'One-Click Creative Generation',
    f2_desc: 'Enter text or upload calligraphy. Choose from minimalist frames, Chinese scrolls, T-shirt prints, phone cases and more. AI renders a product preview instantly — order with one click.',
    f2_tag: 'AI Render · Instant Preview',
    f3_title: 'Cross-Border Creative Shop',
    f3_desc: 'Tiered product system covering starter kits, advanced packs, gift boxes, and subscription boxes. Global delivery via cross-border supply chain.',
    f3_tag: 'Global Delivery · Commerce Loop',

    how_title: 'How It Works',
    how_sub: 'Four steps from practice to creative product',
    step1_title: 'Practice',
    step1_desc: 'Copy copybooks and complete calligraphy practice',
    step2_title: 'Upload',
    step2_desc: 'AI smart recognition and feedback',
    step3_title: 'Choose Template',
    step3_desc: 'Pick your favorite creative product template',
    step4_title: 'Order',
    step4_desc: 'Satisfied with preview, order for global delivery',

    products_title: 'Creative Product Series',
    products_sub: 'Bringing the beauty of calligraphy into everyday life',
    p1_title: 'Minimalist Frame', p1_desc: 'Modern minimalist style, calligraphy wall art',
    p2_title: 'Chinese Scroll', p2_desc: 'Traditional craft, elegant collectible',
    p3_title: 'T-Shirt Print', p3_desc: 'Custom design, wear calligraphy style',
    p4_title: 'Phone Case', p4_desc: 'Carry beauty everywhere',
    p5_title: 'Gift Box Set', p5_desc: 'Exquisite packaging, perfect gift',
    p6_title: 'Subscription Box', p6_desc: 'Monthly surprises, continuous growth',

    cta_title: 'Begin Your Calligraphy Journey',
    cta_sub: 'Join InkArk — where tradition meets modern creativity',
    cta_btn: 'Get Started',

    footer: '© 2026 InkArk · Calligraphy Learning & Creative Platform · Inherit Classics, Create the Future',
    footer_sub: '© 2026 InkArk · Inherit Classics, Create the Future',

    teaching_title: 'AI Calligraphy Teaching',
    teaching_sub: 'Tiered Courses · Smart Assessment · Daily Check-in',
    tab_courses: 'Courses',
    tab_eval: 'Assessment',
    tab_checkin: 'Check-in',
    choose_style: 'Choose Script Style',
    kai: '楷', kai_name: 'Regular Script', kai_desc: 'Structured and standard, ideal for beginners',
    xing: '行', xing_name: 'Running Script', xing_desc: 'Fluid and natural, highly practical',
    li: '隶', li_name: 'Clerical Script', li_desc: 'Ancient and dignified, rich in history',
    zhuan: '篆', zhuan_name: 'Seal Script', zhuan_desc: 'Elegant and refined, high artistic value',
    course_list_title: 'Regular Script Beginner Courses',
    course_list_sub: 'Strokes → Radicals → Structure → Composition, 10-15 min each',
    c1_title: 'Lesson 1: Basic Strokes', c1_desc: 'Master the four fundamental stroke techniques', c1_time: '12 min', c1_status: 'Done',
    c2_title: 'Lesson 2: Hooks & Dots', c2_desc: 'Learn hooks, turns, flicks and dots', c2_time: '10 min', c2_status: 'Done',
    c3_title: 'Lesson 3: Common Radicals', c3_desc: 'Water radical, wood radical, mouth radical, etc.', c3_time: '15 min', c3_status: 'In Progress',
    c4_title: 'Lesson 4: Character Structure', c4_desc: 'Layout principles for left-right and top-bottom structures', c4_time: '15 min', c4_status: 'Locked',
    c5_title: 'Lesson 5: Basic Composition', c5_desc: 'Line spacing, character spacing and overall layout', c5_time: '12 min', c5_status: 'Locked',
    continue_btn: 'Continue Lesson 3',
    eval_instant_title: 'Instant Assessment', eval_instant_desc: 'Upload calligraphy. AI extracts stroke skeleton and compares with professional standards to generate scores and suggestions.',
    eval_stage_title: 'Stage Assessment', eval_stage_desc: 'Comprehensive evaluation after completing a stage, generating a detailed report of achievements and weak points.',
    upload_hint: 'Click to upload calligraphy photo',
    upload_hint2: 'JPG / PNG supported. Natural lighting recommended.',
    last_eval: 'Last Assessment Result',
    score_stroke: 'Stroke Quality', score_struct: 'Structure', score_layout: 'Composition', score_total: 'Overall Score',
    ai_advice: 'AI Tip: Horizontal strokes lack finishing pressure. Focus on horizontal stroke drills. Overall character leans left — center the visual weight.',
    streak_label: 'Current Streak', streak_num: '14 Days', streak_hint: '7 more days to earn the Starter Kit reward!',
    checkin_btn: 'Check In Today',
    month_record: 'This Month\'s Check-in',
    week_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    reward_title: 'Reward Progress',
    reward_hint: 'Complete 21 consecutive days to earn a free Starter Stationery Set',

    creative_title: 'One-Click Creative Generation',
    creative_sub: 'Upload calligraphy or enter text to instantly generate custom products',
    input_panel: 'Content Input',
    upload_calligraphy: 'Upload calligraphy photo',
    text_label: 'Or enter text (name, greeting, phrase)',
    text_placeholder: 'e.g. 福, Mountain High Water Long, Happy New Year…',
    tpl_panel: 'Choose Template',
    tpl1: 'Minimalist Frame', tpl2: 'Chinese Scroll', tpl3: 'T-Shirt', tpl4: 'Phone Case', tpl5: 'Folding Fan', tpl6: 'Gift Box',
    generate_btn: 'Generate Preview',
    preview_panel: 'Preview',
    preview_label_suffix: ' · Preview',
    order_btn: 'Order Now',
    regen_btn: 'Regenerate',
    preview_note: 'After ordering, the system auto-generates high-res print files and connects with partner manufacturers for production and delivery.',

    shop_title: 'Cross-Border Creative Shop',
    shop_sub: 'Stationery · Calligraphy Goods · Global Delivery',
    recommend_title: 'Smart Recommendations',
    recommend_sub: 'Recommended for your current stage (Regular Script · Radicals)',
    recommend_badge: 'Recommended',
    add_cart: 'Add to Cart',
    rec_stone_title: 'Duan Inkstone (Beginner)',
    rec_stone_desc: 'For radical practice stage, natural stone, fine ink release',
    rec_paper_title: 'Raw Xuan Paper (50 sheets)',
    rec_paper_desc: 'Designed for radical stage, even absorption, ideal for copying',
    buy: 'Buy',
    customize: 'Customize',
    subscribe: 'Subscribe',
    all_products: 'All Products',
    all_products_sub: 'Stationery and creative goods — a learning-to-commerce loop',
    filter_all: 'All', filter_stationery: 'Stationery', filter_creative: 'Creative Goods', filter_bundle: 'Gift Sets',

    community_title: 'Calligraphy Community',
    community_sub: 'Share Works · Exchange Tips · Grow Together',
    post_btn: '+ Share My Calligraphy',
    post1_name: 'CloudInk', post1_time: '2 hours ago · Running Script', post1_text: 'Been practicing the character 永 for a while. Still feels unnatural. Any tips from the masters?',
    post2_name: 'MountainStream', post2_time: '5 hours ago · Regular Script', post2_text: 'Practiced these four characters for two weeks and finally feel it. InkArk AI scored me 88 — keep going!',
    post3_name: 'BambooBreeze', post3_time: 'Yesterday · Regular Script', post3_text: 'Regular script 福 character — planning to make it into a custom frame for my parents. Results exceeded expectations!',
    share: '↗ Share',
    activity1_badge: 'Active', activity1_title: 'April Check-in Challenge', activity1_desc: 'Practice daily for 21 days to earn a free Starter Stationery Set.', activity1_count: '1,248 participants', activity1_btn: 'Join Now',
    activity2_badge: 'Coming Soon', activity2_title: 'May Theme: Spring', activity2_desc: 'Create calligraphy on the theme of "Spring". Top works featured on homepage with point rewards.', activity2_date: 'Starts May 1',
    top_creators: 'Top Creators',
    likes_prefix: 'Likes: ',

    profile_title: 'My Profile',
    profile_sub: 'Learning Stats · Orders · Points',
    user_name: 'InkArk Student', user_days: 'Joined 32 days ago', user_level: 'Regular Script · Advancing',
    menu_data: '📊 Learning Stats', menu_orders: '📦 My Orders', menu_points: '⭐ Points',
    stat_days: 'Days', stat_courses: 'Courses', stat_practice: 'Practices', stat_streak: 'Streak',
    radar_title: 'Score Analysis',
    radar_labels: ['Strokes', 'Structure', 'Composition', 'Average'],
    spend_title: 'Purchase Data',
    spend_total: 'Total Spent', spend_items: 'Items Bought', spend_custom: 'Custom Orders', spend_months: 'Subscriptions',
    order1_name: 'Custom Calligraphy Frame', order1_date: '2026-04-10 · Order HM20260410001', order1_status: 'Shipping',
    order2_name: 'Starter Gift Box', order2_date: '2026-03-28 · Order HM20260328002', order2_status: 'Completed',
    order3_name: 'Monthly Subscription Box · Apr', order3_date: '2026-04-01 · Order HM20260401003', order3_status: 'Preparing',
    points_label: 'Current Points', points_exchange: 'Redeem Points',
    pt1_name: 'Completed Lesson 2', pt2_name: 'Uploaded Practice Work', pt3_name: 'Purchased Starter Gift Box',

    // Shop products
    sp_brush1_title: 'Goat Hair Brush', sp_brush1_desc: 'Soft & absorbent, ideal for Regular/Running script beginners',
    sp_brush2_title: 'Weasel Hair Fine Brush', sp_brush2_desc: 'Firm & sharp tip, great for small Regular script',
    sp_brush3_title: 'Mixed Hair Medium Brush', sp_brush3_desc: 'Balanced flex, suits medium Regular script',
    sp_brush4_title: 'Large Goat Hair Brush', sp_brush4_desc: 'Full belly, smooth flow, for large-character practice',
    sp_brush5_title: 'Small Script Brush', sp_brush5_desc: 'Balanced stiffness, suits tracing and copying',
    sp_ink1_title: 'Pine Soot Ink (500ml)', sp_ink1_desc: 'Deep black, rich aroma, for daily Regular/Clerical practice',
    sp_ink2_title: 'Oil Soot Ink (250ml)', sp_ink2_desc: 'Glossy finish, fade-resistant, for exhibitions',
    sp_ink3_title: 'Concentrated Ink', sp_ink3_desc: 'High-density formula, dilute as needed, smooth writing',
    sp_ink4_title: 'Color Ink Set', sp_ink4_desc: 'Multi-color, vivid saturation, for creative calligraphy',
    sp_ink5_title: 'Traditional Hand-Ground Ink', sp_ink5_desc: 'Artisan craft, fine texture, for advanced work',
    sp_stone1_title: 'Duan Inkstone (Beginner)', sp_stone1_desc: 'Natural stone, fine ink release, for daily practice',
    sp_stone2_title: 'Duan Inkstone (Advanced)', sp_stone2_desc: 'Fine stone, elegant carving, for advanced practice',
    sp_stone3_title: 'She Inkstone (Collector)', sp_stone3_desc: 'Premium She stone, natural grain, collectible & functional',
    sp_stone4_title: 'Chengni Inkstone (Gift)', sp_stone4_desc: 'Fired clay, warm texture, great for gifting',
    sp_stone5_title: 'Songhua Inkstone (Scholar)', sp_stone5_desc: 'Songhua stone carving, calm tone, scholar\'s essential',
    sp_stone6_title: 'Red Silk Inkstone (Master)', sp_stone6_desc: 'Red silk stone, cloud-like grain, master-recommended',
    sp_paper1_title: 'Raw Xuan Paper (50 sheets)', sp_paper1_desc: 'Even ink absorption, ideal for Regular script copying',
    sp_paper2_title: 'Semi-processed Xuan (30 sheets)', sp_paper2_desc: 'Between raw and sized, suits Running & Cursive script',
    sp_paper3_title: 'Sized Tracing Paper (40 sheets)', sp_paper3_desc: 'No bleeding, perfect for beginner tracing',
    sp_paper4_title: 'Gold-flecked Xuan (20 sheets)', sp_paper4_desc: 'Gold foil accents, for artwork creation & display',
    sp_paper5_title: 'Antique Xuan (25 sheets)', sp_paper5_desc: 'Aged finish, classic elegance, for art & collection',
    sp_paper6_title: 'Cloud Dragon Xuan (20 sheets)', sp_paper6_desc: 'Cloud dragon texture, unique feel, top choice for creation',
    sp_cr1_title: 'Mini Scroll', sp_cr1_desc: 'Compact size, for practice and creative pieces',
    sp_cr2_title: 'Full-silk Hanging Scroll', sp_cr2_desc: 'Premium silk mounting, for calligraphy display',
    sp_cr3_title: 'Blank Folding Fan', sp_cr3_desc: 'Quality bamboo frame, customizable calligraphy',
    sp_cr4_title: 'Chinese Style Fan', sp_cr4_desc: 'Silk material, artistic design, summer essential',
    sp_cr5_title: 'Traditional Folding Fan', sp_cr5_desc: 'Handcrafted, floral & landscape patterns, classic elegance',
    sp_cr6_title: 'Calligraphy Frame', sp_cr6_desc: 'Wood-finish frame, modern minimalist, showcase your work',
    sp_cr7_title: 'Song Brocade Desk Stand', sp_cr7_desc: 'Brocade backing, hard card writing surface, heartfelt gift',
    sp_bd1_title: 'Starter Kit', sp_bd1_desc: 'Beginner brush, 10 sheets Xuan paper, ready to learn',
    sp_bd2_title: 'Master Kit', sp_bd2_desc: 'Antique brush, gold Xuan paper, Lanting Xu tracing sheet',
    sp_bd3_title: 'Gift Box', sp_bd3_desc: 'Four Treasures, culture booklet, premium gift packaging',
    sp_bd4_title: 'Subscription Box', sp_bd4_desc: 'Monthly tools + culture reads + creative tasks',
  }
};

function getLang() {
  return localStorage.getItem('hmLang') || 'zh';
}

function setLang(lang) {
  localStorage.setItem('hmLang', lang);
}

function t(key) {
  const lang = getLang();
  return TRANSLATIONS[lang][key] || TRANSLATIONS['zh'][key] || key;
}
